# Generated by Django 5.2 on 2025-05-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamento_financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='cod_classe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='cod_grupo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lancamentofinanceiro',
            name='cod_natureza',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
