# Generated by Django 5.2 on 2025-04-30 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoContas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_classe', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=100)),
                ('cod_grupo', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=100)),
                ('cod_natureza', models.CharField(max_length=100)),
                ('natureza', models.CharField(max_length=100)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plano Conta',
                'verbose_name_plural': 'Planos Contas',
            },
        ),
    ]
